codeunit 51003 "TOO TAR Mgt."
{
    /* Cloud compatible TAR archive fast reading/writing
       ustar format with pax header
       This format can be by windows embeded archive explorer and 7zip

     Creat/Write :
        CreateTarArchive();
        WriteTarEntry(FileInStream: InStream; EntryName: Text);
        SaveTarArchive(OutStream: OutStream)

     Read :
        IsTAR(InputInStream: InStream): Boolean
        OpenTarArchive(TarInStreamParam: InStream)
        GetEntryList(var EntryList: List of [Text])
        ExtractEntry(EntryName: Text; var FileOutStream: OutStream)

        Note : for faster files extraction, first call GetEntryList to build files position dictionnay and avoid full scan at each file.
    */

    var
        Base64Convert: Codeunit "Base64 Convert";
        TempBlob: Codeunit "Temp Blob";
        ZeroBlob: Codeunit "Temp Blob";
        OpenedInStream: InStream;
        Mtime: BigInteger;
        FinalBlockWritten: Boolean;
        IsBase64Initialized: Boolean;
        IsZeroBlobInitialized: Boolean;
        EntryIndex: Dictionary of [Text, BigInteger]; // Name -> Position in stream
        ZeroBlobInStr: InStream;
        Base64RevMap: array[128] of Integer;          // base64 char code -> 6-bit value
        EntryNames: List of [Text];                   // cached list of file names (order preserved)
        TarOutStream: OutStream;
        Base64Alphabet: Text;
        ZeroBlockBase64: Text;                        // base64 of a 512-byte zero block (end-of-archive marker)

    procedure IsTAR(var InputInStream: InStream): Boolean
    var
        HeaderFound: Boolean;
        Header: array[512] of Byte; // TAR header block
    begin
        if InputInStream.Length < 512 then
            exit(false); // Not enough data for a header block

        HeaderFound := ReadHeader(InputInStream, Header);
        InputInStream.Position := 1; // Reset the stream for reuse
        if not HeaderFound then
            exit(false);

        // Magic 'ustar' at bytes 258–262 (AL is 1-based; 257–261 in zero-based indexing)
        exit((Header[258] = 117) and (Header[259] = 115) and (Header[260] = 116) and
             (Header[261] = 97) and (Header[262] = 114));
    end;

    #region Write TAR


    procedure CreateTarArchive()
    var
        DataSize: BigInteger;
        Padding: BigInteger;
        Sum: BigInteger;
        Header: array[512] of Byte;
        CharZero: Char;
        DL: Integer;
        i: Integer;
        L: Integer;
        PrevDL: Integer;
        Attr: Text;
        ChecksumOctal: Text;
        ExtendedData: Text;
        Line: Text;
    begin
        FinalBlockWritten := false;
        Clear(TempBlob);
        TempBlob.CreateOutStream(TarOutStream);
        Mtime := (CurrentDateTime - CreateDateTime(19700101D, 000000T)) div 1000;
        InitializeZeroBlob();

        // Add a global PAX header to make the archive PAX-compatible (starts with 'pax_global_header')
        // This helps with compatibility, e.g., for UTF-8 or extended attributes, and ensures Windows can handle it properly
        CharZero := 0;
        Clear(Header);

        // Name
        SetStringToBytes(Header, 1, 'pax_global_header');

        // Mode: 0000000\0
        SetStringToBytes(Header, 101, '0000000' + CharZero);

        // UID: 0000000\0
        SetStringToBytes(Header, 109, '0000000' + CharZero);

        // GID: 0000000\0
        SetStringToBytes(Header, 117, '0000000' + CharZero);

        // Size: to be set later as octal
        // MTime: 00000000000\0
        SetStringToBytes(Header, 137, '00000000000' + CharZero);

        // Checksum: initially spaces
        for i := 149 to 156 do
            Header[i] := 32;

        // Typeflag: 'g' for global extended header
        Header[157] := 103; // Ord('g');

        // Linkname: empty

        // Magic: ustar\0 (but for PAX, it's ustar\0)
        SetStringToBytes(Header, 258, 'ustar' + CharZero);

        // Version: 00
        SetStringToBytes(Header, 264, '00');

        // Uname: root
        SetStringToBytes(Header, 266, 'root');

        // Gname: root
        SetStringToBytes(Header, 298, 'root');

        // Devmajor: 0000000\0
        SetStringToBytes(Header, 330, '0000000' + CharZero);

        // Devminor: 0000000\0
        SetStringToBytes(Header, 338, '0000000' + CharZero);

        // Prefix: empty

        // Prepare extended data (example: a comment; you can add more attributes like hdrcharset=UTF-8)
        Attr := 'comment=Generated by Microsoft Dynamics 365 Business Central';
        Line := Attr + '\n';
        L := StrLen(Line);
        DL := 2; // Initial guess for digits in length
        repeat
            PrevDL := DL;
            L := StrLen(Line) + DL + 1; // length digits + space + attr line
            DL := StrLen(Format(L));
        until DL = PrevDL;
        ExtendedData := Format(L) + ' ' + Attr + '\n';
        DataSize := StrLen(ExtendedData);

        // Set size in octal (11 digits + \0)
        SetStringToBytes(Header, 125, GetOctal(DataSize, 11) + CharZero);

        // Calculate checksum
        Sum := 0;
        for i := 1 to 512 do
            Sum += Header[i];
        ChecksumOctal := GetOctal(Sum, 6);
        SetStringToBytes(Header, 149, ChecksumOctal);
        Header[155] := 0; // NUL after 6 digits
        Header[156] := 32; // Space

        // Write the header
        WriteBlock(Header, 512);

        // Write the extended data
        SetStringToBytes(Header, 1, ExtendedData); // Reuse Header array for data since small
        WriteBlock(Header, DataSize);

        // Padding for data
        Padding := (512 - (DataSize mod 512)) mod 512;
        if Padding > 0 then
            WriteZeros(Padding);

        // Now the archive is initialized with the global PAX header. You can add file entries after this.
    end;

    procedure WriteTarEntry(FileInStream: InStream; EntryName: Text)
    var
        FileSize: BigInteger;
        PaddingSize: BigInteger;
        Header: array[512] of Byte;
        Checksum: Integer;
        i: Integer;
    begin
        FileInStream.ResetPosition();
        FileSize := FileInStream.Length;
        Clear(Header);
        // File name
        WriteStringToHeader(Header, 1, 100, EntryName);
        // Mode: 0644 octal (420 decimal)
        WriteOctalToHeader(Header, 101, 8, 420);
        // UID: 0
        WriteOctalToHeader(Header, 109, 8, 0);
        // GID: 0
        WriteOctalToHeader(Header, 117, 8, 0);
        // Size
        WriteOctalToHeader(Header, 125, 12, FileSize);
        // Mtime: Unix timestamp
        WriteOctalToHeader(Header, 137, 12, Mtime);
        // Typeflag: '0' for normal file
        Header[157] := '0';
        // Magic: "ustar\0"
        Header[258] := 'u';
        Header[259] := 's';
        Header[260] := 't';
        Header[261] := 'a';
        Header[262] := 'r';
        Header[263] := 0;
        // Version: "00"
        Header[264] := '0';
        Header[265] := '0';
        // User name: "root"
        WriteStringToHeader(Header, 266, 32, 'root');
        // Group name: "root"
        WriteStringToHeader(Header, 298, 32, 'root');
        // Dev major: 0
        WriteOctalToHeader(Header, 329, 8, 0);
        // Dev minor: 0
        WriteOctalToHeader(Header, 337, 8, 0);
        // Set checksum field to 8 spaces for calculation
        for i := 149 to 156 do
            Header[i] := 32;
        // Calculate checksum
        Checksum := 0;
        for i := 1 to 512 do
            Checksum += Header[i];
        // Write checksum: 6 octal digits, \0, space
        WriteChecksumToHeader(Header, 149, Checksum);
        // Write header to stream (single bulk write - byte-per-byte stream I/O is the perf killer)
        WriteBlock(Header, 512);
        // Copy file data
        CopyStream(TarOutStream, FileInStream);
        // Padding to next 512-byte block
        PaddingSize := FileSize mod 512;
        if PaddingSize <> 0 then
            PaddingSize := 512 - PaddingSize;
        WriteZeros(PaddingSize);
    end;

    procedure WriteTarEntry(FileContent: Text; EntryName: Text)
    var
        TempBlob: Codeunit "Temp Blob";
        OutStr: OutStream;
    begin
        OutStr := TempBlob.CreateOutStream();
        OutStr.Write(FileContent);
        WriteTarEntry(TempBlob.CreateInStream(), EntryName);
    end;

    procedure SaveTarArchive(var OutStream: OutStream)
    var
        TarInStream: InStream;
    begin
        // Write two zero-filled 512-byte blocks to end the archive
        if not FinalBlockWritten then
            WriteZeros(1024);
        // Copy the entire archive to the output stream
        TempBlob.CreateInStream(TarInStream);
        CopyStream(OutStream, TarInStream);
    end;

    procedure SaveTarArchive(var vTempBlob: Codeunit "Temp Blob")
    begin
        // Write two zero-filled 512-byte blocks to end the archive
        if not FinalBlockWritten then
            WriteZeros(1024);
        vTempBlob := TempBlob;
    end;

    procedure SaveTarArchive(var TarInStream: InStream)
    begin
        // Write two zero-filled 512-byte blocks to end the archive
        if not FinalBlockWritten then
            WriteZeros(1024);
        // Copy the entire archive to the output stream
        TempBlob.CreateInStream(TarInStream);
    end;
    #endregion

    #region Read TAR
    procedure OpenTarArchive(var TarInStreamParam: InStream)
    begin
        Clear(TempBlob);
        clear(OpenedInStream);
        OpenedInStream := TarInStreamParam;
        OpenedInStream.ResetPosition();
        if not IsTAR(OpenedInStream) then
            Error('The instream is not a valid TAR file');
        // Clear any existing index
        Clear(EntryIndex);
    end;

    procedure GetEntryList(var Names: List of [Text])
    begin
        if EntryIndex.Count = 0 then
            BuildIndexAndGetNames(Names)
        else
            Names := EntryNames;  // Already cached
    end;

    procedure ExtractEntry(EntryName: Text; FileOutStream: OutStream)
    var
        Padding: BigInteger;
        Size: BigInteger;
        StartPos: BigInteger;
        Found: Boolean;
        Header: array[512] of Byte;
        Name: Text;
    begin
        // Optimization: If index exists, seek directly to the entry's data position
        if EntryIndex.ContainsKey(EntryName) then begin
            StartPos := EntryIndex.Get(EntryName);
            OpenedInStream.Position := StartPos - 512; // Back up to header start
            if not ReadHeader(OpenedInStream, Header) then
                Error('Invalid index for entry "%1".', EntryName);
            Size := GetSizeFromHeader(Header); // Still need size
            CopyStream(FileOutStream, OpenedInStream, Size);
            exit;
        end;
        // Fallback: Sequential scan
        Found := false;
        OpenedInStream.ResetPosition();
        while (not Found) and ReadHeader(OpenedInStream, Header) do begin
            Name := GetFullNameFromHeader(Header);
            if Name = EntryName then begin // Check name before computing size (cheaper)
                Found := true;
                Size := GetSizeFromHeader(Header);
                CopyStream(FileOutStream, OpenedInStream, Size);
            end else begin
                Size := GetSizeFromHeader(Header);
                OpenedInStream.Position := OpenedInStream.Position + Size; // skip size
                Padding := (512 - (Size mod 512)) mod 512;
                OpenedInStream.Position := OpenedInStream.Position + Padding; // skip size
            end;
        end;
        if not Found then
            Error('Entry "%1" not found in the archive.', EntryName);
    end;
    #endregion

    #region Tech. Read
    local procedure BuildIndexAndGetNames(var Names: List of [Text]): Boolean
    var
        DataStartPos: BigInteger;
        Padding, Size : BigInteger;
        Header: array[512] of Byte;
        //InStr: InStream;
        Name: Text;
    begin
        Clear(EntryIndex);
        Clear(EntryNames);
        Clear(Names);

        //TempBlob.CreateInStream(InStr);
        if OpenedInStream.Length = 0 then exit;
        OpenedInStream.ResetPosition();
        while ReadHeader(OpenedInStream, Header) do begin
            DataStartPos := OpenedInStream.Position;         // Position = right after the 512-byte header
            Name := GetFullNameFromHeader(Header);

            if Name <> '' then begin
                EntryIndex.Add(Name, DataStartPos);
                EntryNames.Add(Name);
                Names.Add(Name);                        // Return ordered list
            end;

            Size := GetSizeFromHeader(Header);
            OpenedInStream.Position := OpenedInStream.Position + Size; // skip size
            Padding := (512 - (Size mod 512)) mod 512;
            OpenedInStream.Position := OpenedInStream.Position + Padding; // skip Padding
        end;

        exit(EntryIndex.Count > 0);
    end;

    local procedure ReadHeader(var InStr: InStream; var Header: array[512] of Byte): Boolean
    var
        HeaderBlob: Codeunit "Temp Blob";
        BlobInStream: InStream;
        BlobOutStream: OutStream;
        HeaderBase64: Text;
    begin
        // Bulk read: byte-per-byte InStream.Read costs one interop call per byte (512/header).
        // Copy the block + base64 it in 2 calls, then decode in pure AL.
        if not IsBase64Initialized then
            InitializeBase64();
        if InStr.Length - InStr.Position + 1 < 512 then
            exit(false);
        HeaderBlob.CreateOutStream(BlobOutStream);
        CopyStream(BlobOutStream, InStr, 512);
        HeaderBlob.CreateInStream(BlobInStream);
        HeaderBase64 := Base64Convert.ToBase64(BlobInStream);
        if HeaderBase64 = ZeroBlockBase64 then
            exit(false); // All-zero block = end of archive, no decode needed
        DecodeBase64Block(HeaderBase64, Header);
        exit(true);
    end;

    local procedure InitializeBase64()
    var
        i: Integer;
    begin
        if IsBase64Initialized then
            exit;
        Base64Alphabet := 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
        for i := 1 to 64 do
            Base64RevMap[Base64Alphabet[i] + 1] := i - 1;
        ZeroBlockBase64 := PadStr('', 683, 'A') + '='; // 512 zero bytes encoded
        IsBase64Initialized := true;
    end;

    local procedure EncodeBase64Block(var Buf: array[512] of Byte; Len: Integer): Text
    var
        B1, B2, B3 : Integer;
        i, j : Integer;
        Base64Text: Text;
    begin
        // Pure AL base64 encode of Buf[1..Len]; decoded back to raw bytes by "Base64 Convert" in one call
        if not IsBase64Initialized then
            InitializeBase64();
        Base64Text := PadStr('', ((Len + 2) div 3) * 4, '='); // Preallocate, tail '=' = padding
        i := 1;
        j := 1;
        while i + 2 <= Len do begin
            B1 := Buf[i];
            B2 := Buf[i + 1];
            B3 := Buf[i + 2];
            Base64Text[j] := Base64Alphabet[B1 div 4 + 1];
            Base64Text[j + 1] := Base64Alphabet[(B1 mod 4) * 16 + B2 div 16 + 1];
            Base64Text[j + 2] := Base64Alphabet[(B2 mod 16) * 4 + B3 div 64 + 1];
            Base64Text[j + 3] := Base64Alphabet[B3 mod 64 + 1];
            i += 3;
            j += 4;
        end;
        case Len - i + 1 of
            1:
                begin
                    B1 := Buf[i];
                    Base64Text[j] := Base64Alphabet[B1 div 4 + 1];
                    Base64Text[j + 1] := Base64Alphabet[(B1 mod 4) * 16 + 1];
                end;
            2:
                begin
                    B1 := Buf[i];
                    B2 := Buf[i + 1];
                    Base64Text[j] := Base64Alphabet[B1 div 4 + 1];
                    Base64Text[j + 1] := Base64Alphabet[(B1 mod 4) * 16 + B2 div 16 + 1];
                    Base64Text[j + 2] := Base64Alphabet[(B2 mod 16) * 4 + 1];
                end;
        end;
        exit(Base64Text);
    end;

    local procedure DecodeBase64Block(Base64Text: Text; var Header: array[512] of Byte)
    var
        C1, C2, C3, C4 : Integer;
        i, j : Integer;
    begin
        // Pure AL decode of a 684-char base64 string (exactly 512 bytes: 170 full groups + 2 tail bytes)
        j := 1;
        for i := 1 to 170 do begin
            C1 := Base64RevMap[Base64Text[j] + 1];
            C2 := Base64RevMap[Base64Text[j + 1] + 1];
            C3 := Base64RevMap[Base64Text[j + 2] + 1];
            C4 := Base64RevMap[Base64Text[j + 3] + 1];
            Header[i * 3 - 2] := C1 * 4 + C2 div 16;
            Header[i * 3 - 1] := (C2 mod 16) * 16 + C3 div 4;
            Header[i * 3] := (C3 mod 4) * 64 + C4;
            j += 4;
        end;
        C1 := Base64RevMap[Base64Text[681] + 1];
        C2 := Base64RevMap[Base64Text[682] + 1];
        C3 := Base64RevMap[Base64Text[683] + 1];
        Header[511] := C1 * 4 + C2 div 16;
        Header[512] := (C2 mod 16) * 16 + C3 div 4;
    end;

    local procedure WriteBlock(var Buf: array[512] of Byte; Len: Integer)
    var
        i: Integer;
    begin
        for i := 1 to Len do
            TarOutStream.Write(Buf[i]);
    end;

    local procedure GetFullNameFromHeader(var Header: array[512] of Byte): Text
    var
        i, Pos : Integer;
        Result: Text[512];
    begin
        Pos := 0;

        // Check USTAR
        if (Header[258] = 117) and (Header[259] = 115) and (Header[260] = 116) and
           (Header[261] = 97) and (Header[262] = 114) and (Header[263] = 0) then begin
            for i := 346 to 500 do begin
                if Header[i] = 0 then
                    break;
                Pos += 1;
                Result[Pos] := Header[i];
            end;
            if Pos > 0 then begin
                Pos += 1;
                Result[Pos] := 47; // '/'
            end;
        end;

        for i := 1 to 100 do begin
            if Header[i] = 0 then
                break;
            Pos += 1;
            Result[Pos] := Header[i];
        end;

        exit(CopyStr(Result, 1, Pos));
    end;

    local procedure GetSizeFromHeader(var Header: array[512] of Byte): BigInteger
    var
        i, Pos : Integer;
        Octal: Text[12];
        // From Octal inlined :
        Value: BigInteger;
        Digit: Integer;
        j: Integer;
    begin
        Pos := 0;
        for i := 125 to 136 do begin
            if Header[i] = 0 then
                break;
            Pos += 1;
            Octal[Pos] := Header[i];
        end;
        Octal := Octal.Trim(); // Remove spaces
        if Octal = '' then
            exit(0);
        // FromOctal(Octal) inlined  :
        Value := 0;
        for j := 1 to StrLen(Octal) do begin
            Digit := Octal[j] - 48; // '0'
            if (Digit < 0) or (Digit > 7) then
                Error('Invalid octal digit in size field.');
            Value := Value * 8 + Digit;
        end;
        exit(Value);
    end;
    #endregion

    #region Tech. Write
    local procedure SetStringToBytes(var Arr: array[512] of Byte; StartPos: Integer; Str: Text)
    var
        j: Integer;
    begin
        for j := 1 to StrLen(Str) do
            Arr[StartPos + j - 1] := Str[j];
    end;

    local procedure ToOctal(Value: BigInteger; Len: Integer): Text
    var
        Remainder: Integer;
        Octal: Text;
    begin
        Octal := '';
        if Value = 0 then
            Octal := '0';
        while Value > 0 do begin
            Remainder := Value mod 8;
            Octal := Format(Remainder) + Octal;
            Value := Value div 8;
        end;
        while StrLen(Octal) < Len do
            Octal := '0' + Octal;
        exit(Octal);
    end;

    local procedure GetOctal(Value: BigInteger; Digits: Integer): Text
    var
        V: BigInteger;
        Octal: Text;
    begin
        Octal := '';
        V := Value;
        if V = 0 then
            Octal := '0'
        else
            while V > 0 do begin
                Octal := Format(V mod 8) + Octal;
                V := V div 8;
            end;
        while StrLen(Octal) < Digits do
            Octal := '0' + Octal;
        exit(Octal);
    end;

    local procedure WriteStringToHeader(var Header: array[512] of Byte; Pos: Integer; MaxLen: Integer; Value: Text)
    var
        i: Integer;
    begin
        for i := 1 to StrLen(Value) do
            if i <= MaxLen then
                Header[Pos + i - 1] := Value[i];
    end;

    local procedure WriteOctalToHeader(var Header: array[512] of Byte; Pos: Integer; FieldLen: Integer; Value: BigInteger)
    var
        i: Integer;
        Octal: Text;
    begin
        Octal := ToOctal(Value, FieldLen - 1);
        for i := 1 to StrLen(Octal) do
            Header[Pos + i - 1] := Octal[i];
        Header[Pos + FieldLen - 1] := 0;
    end;

    local procedure WriteChecksumToHeader(var Header: array[512] of Byte; Pos: Integer; Value: Integer)
    var
        i: Integer;
        Octal: Text;
    begin
        Octal := ToOctal(Value, 6);
        for i := 1 to 6 do
            Header[Pos + i - 1] := Octal[i];
        Header[Pos + 6] := 0;
        Header[Pos + 7] := 32;
    end;

    local procedure WriteZeros(Size: Integer)
    var
        Chunk: Integer;
    begin
        // ZeroBlob holds one 512-byte zero block; copy it as many times as needed
        while Size > 0 do begin
            Chunk := Size;
            if Chunk > 512 then
                Chunk := 512;
            ZeroBlobInStr.ResetPosition();
            CopyStream(TarOutStream, ZeroBlobInStr, Chunk);
            Size -= Chunk;
        end;
    end;

    procedure InitializeZeroBlob()
    var
        ZeroOutStream: OutStream;
    begin
        if IsZeroBlobInitialized then
            exit;
        InitializeBase64();
        ZeroBlob.CreateOutStream(ZeroOutStream);
        Base64Convert.FromBase64(ZeroBlockBase64, ZeroOutStream); // 512 zero bytes into fresh blob
        IsZeroBlobInitialized := true;
        ZeroBlob.CreateInStream(ZeroBlobInStr);
    end;

    #endregion
}