permissionset 51000 "Imp-Exp Company"
{
    Assignable = true;
    Permissions = tabledata "TOO All Types" = RIMD,
        tabledata "TOO Pipou Archive" = RIMD,
        tabledata "TOO Pipou Archive Dict." = RIMD,
        tabledata "TOO Pipou Archive Fields" = RIMD,
        tabledata "TOO Pipou Archive Files" = RIMD,
        tabledata "TOO Pipou Archive Tables" = RIMD,
        tabledata "TOO Pipou Import Log" = RIMD,
        tabledata "TOO Pipou Thread" = RIMD,
        tabledata "TOO Temp Blob" = RIMD,
        table "TOO All Types" = X,
        table "TOO Pipou Archive" = X,
        table "TOO Pipou Archive Dict." = X,
        table "TOO Pipou Archive Fields" = X,
        table "TOO Pipou Archive Files" = X,
        table "TOO Pipou Archive Tables" = X,
        table "TOO Pipou Import Log" = X,
        table "TOO Pipou Thread" = X,
        table "TOO Temp Blob" = X,
        codeunit "TOO Advanced Compression Mgt." = X,
        codeunit "TOO Pipou Archive Meta Mgt." = X,
        codeunit "TOO Pipou Blob Mgt." = X,
        codeunit "TOO Pipou colstore Mgt." = X,
        codeunit "TOO Pipou Export Data" = X,
        codeunit "TOO Pipou Import Data" = X,
        codeunit "TOO Pipou Import Events" = X,
        codeunit "TOO Pipou Import Multithreads" = X,
        codeunit "TOO Pipou Mgt." = X,
        codeunit "TOO Pipou Threads Mgt." = X,
        codeunit "TOO TAR Mgt." = X,
        codeunit "TOO WriteInsideTryEnabled" = X,
        page "TOO Pipou Archive Card" = X,
        page "TOO Pipou Archive Fields" = X,
        page "TOO Pipou Archive Files" = X,
        page "TOO Pipou Archive Tables" = X,
        page "TOO Pipou Archives" = X,
        page "TOO Pipou Export Asst. Setup" = X,
        page "TOO Pipou Export Fields" = X,
        page "TOO Pipou Export Tables Sub" = X,
        page "TOO Pipou Import Asst. Setup" = X,
        page "TOO Pipou Import Logs" = X,
        page "TOO Pipou Import Tables Sub" = X,
        page "TOO Pipou Threads" = X,
        page "TOO Upload File JS" = X;
}